# Generated by Django 2.2 on 2021-07-20 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg_app', '0004_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=45)),
                ('post_date', models.DateField()),
                ('salary_min', models.IntegerField(blank=True, default=None, max_length=12)),
                ('salary_max', models.IntegerField(blank=True, default=None, max_length=12)),
                ('job_url', models.CharField(max_length=255)),
                ('job_desc', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('dislikes', models.ManyToManyField(related_name='job_dislikes', to='login_reg_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('duration', models.IntegerField(default=None, max_length=2)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('pos_saves', models.ManyToManyField(related_name='user_pos_saves', to='login_reg_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_reg_app.User')),
                ('job_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobSearch_app.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=45)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('loc_saves', models.ManyToManyField(related_name='user_loc_saves', to='login_reg_app.User')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobSearch_app.State')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobSearch_app.Position'),
        ),
        migrations.AddField(
            model_name='job',
            name='likes',
            field=models.ManyToManyField(related_name='job_likes', to='login_reg_app.User'),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobSearch_app.Location'),
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.ManyToManyField(related_name='qual_jobs', to='jobSearch_app.Qualification'),
        ),
    ]
