# Generated by Django 2.2 on 2021-07-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSearch_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=45),
        ),
    ]
