# Generated by Django 2.2 on 2021-07-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSearch_app', '0002_auto_20210719_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_max',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_min',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='duration',
            field=models.IntegerField(default=None),
        ),
    ]
