# Generated by Django 2.2 on 2021-07-26 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobSearch_app', '0008_auto_20210720_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='login_reg_app.User'),
        ),
        migrations.AlterField(
            model_name='note',
            name='job_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='jobSearch_app.Job'),
        ),
    ]
