# Generated by Django 2.2 on 2021-07-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobSearch_app', '0010_accomplishments_commonqa_elevatorpitch_general_strength_weakness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='abbr',
            field=models.CharField(max_length=2),
        ),
    ]
